---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: vbox/debian10
    driver:
      box: debian10
      provider: virtualbox

verifier:
  name: inspec

suites:
  - name: default
