---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: vbox/debian10
    driver:
      box: packer-debian-10-amd64
      provider: virtualbox

verifier:
  name: inspec

suites:
  - name: default
